name: Release version

on:
  workflow_dispatch:

jobs:
  autoincrement:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configure Git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Close version
        run: |
          CURRENT_VERSION=$(./mvnw -B --no-transfer-progress help:evaluate -Dexpression=revision -q -DforceStdout)
          BASE_VERSION=${CURRENT_VERSION%-SNAPSHOT} # Remove -SNAPSHOT
          ./mvnw -B --no-transfer-progress versions:set-property -Dproperty=revision -DnewVersion=$BASE_VERSION
          ./mvnw -B --no-transfer-progress versions:commit

      - name: Commit changed and create Git tag
        run: |
          VERSION=$(./mvnw -B --no-transfer-progress help:evaluate -Dexpression=revision -q -DforceStdout)
          find . -name 'pom.xml' | xargs git add
          git commit -m "Tagged version v${VERSION} [skip-ci]"
          git push
          
          git tag v$VERSION
          git push origin v$VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment version and append -SNAPSHOT
        run: |
          NEXT_SNAPSHOT=$(./mvnw -B --no-transfer-progress help:evaluate -Dexpression=revision -q -DforceStdout | awk -F. -v OFS=. '{$NF += 1 ; print}')-SNAPSHOT
          ./mvnw -B --no-transfer-progress versions:set-property -Dproperty=revision -DnewVersion=$NEXT_SNAPSHOT
          ./mvnw -B --no-transfer-progress versions:commit
          git commit -m "Increment version to ${NEXT_SNAPSHOT} [skip-ci]"
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
